<a href="https://colab.research.google.com/github/ckxmrls/kayedocs/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ECE
##Laboratory 4 :Matrices

## Objectives
At the end of this activity you will be able to:


1.   Be familiar with matrices and their relation to linear equation
2.   Perform basic matrx operations
3.   Program and translate matrixequations and operationsusing Python






##Discussion

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representation of complex equation or multiple inter - related equations from 2 dimentional equations to even hundreds and thousands of others

Let's say for example you have ***A*** and ***B*** as the system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that ***A*** is a system of 2 equations with 2 parameters, While ***B*** is a system of 3 equation with 3 parameters. We can represent
them as matrices:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

##Declaring Matrices
We must start the matrix, but we do not want to use a loop in a lengthier method. For that, we need an abstract. In dynamic programming, this sort of problem is extremely prevalent.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [6]:
## since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [7]:
## Declaring a 2 x 2 matrix
A = np.array([
             [1, 2],
             [3, 1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [8]:
G = np.array([
              [1, 1],
              [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [9]:
## Declaring a 3 x 2 matrix:
B = np.array([
              [8, 2],
              [5,4],
              [1, 1]       
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [10]:
H = np.array([1, 2, 3, 4, 5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



#Categorizing Matrices


There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values**. We'll try to go through them.

##According to Shape

###Row and Column Matrices


Row and Column Matrices are common in vector and matrix computation. They can also represent row and column spaces of a bigger vector space. It is represented by a single column or a single row.

In [11]:
## Declaring a Row Matrix

row_mat_1D = np.array([
                       1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
                       [1, 2, 3]
]) ## this is a 2-D Matrix with a shape of (1, 3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [12]:
## Declaring a Column Matrix

col_mat = np.array([
                    [1],
                    [2],
                    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



##Square Matrices

Square Matrices are matrices that have the same row and column sizes. We could say a matrix is square if *i* - *j*. We can tweak our matrix descriptor function to determine square matrices.

In [13]:
def describe_mat(matrix):
  is_square = True if matrix.shape [0] -- matrix.shape[1] else False 
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
                             [1, 2, 5],
                             [3, 3, 0],
                             [6, 1, 2]
])

non_square_mat = np.array([
                           [1, 2, 5],
                           [3, 3, 0]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 0]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 0]]

Shape:	(2, 3)
Rank:	2
Is Square: True



##According to Element Values

##Null Matrix

A Null Matrix is a matrix that has element. It is always a subsplace of any vector or matrix. 

In [20]:
def describe_mat (matrix):
  if matrix. size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n') 
  else:
      print('Matrix is Null')

In [21]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


##Zero Matrix

A zero matrix is considered to be a matrix adding identity element. In matrix arithmetic, a null matrix performs some of the same purposes as 0 in conventional arithmetic.

In [23]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix

An all-one matrix or one matrix matrix is a matrix in which each member is equal. Some authors name the all-one matrix the matrix, although the phrase might alternatively use a distinct matrix, the identity matrix.

In [25]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##Diagonal Matrix

A matrix's primary diagonal is made up of the components that run from top left to bottom right. If the matrix is A, the elements with the same row and column number form the matrix's major diagonal.

In [26]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [28]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

##Identity Matrix

A square matrix with on the main diagonal and everywhere else is an identity matrix. The identity matrices are depicted below. These are known as identity matrices because they produce the identical matrix when multiplied by a compatible matrix.

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Upper Triangular Matrix


All of the values the major diagonal in the top triangular matrix are zero. A lower triangular matrix is one that contains members above the main diagonal that are all zero.

In [32]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

##Lower Triangular Matrix

A lower triangular matrix is one that has all of its upper triangular elements equal to zero. In other words, all non-zero elements are on the main diagonal or in the bottom triangle. Because they have zeros above and below the major diagonal, diagonal matrices are both upper and lower triangular.

In [33]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

##Matrix Algebra

###Addition

In [34]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [36]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

###Subtraction

In [37]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [38]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

###Element-wise Multiplication

In [39]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [40]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [45]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [46]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

#Activity

##Task1

Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared

##Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

###Conclusion