<a href="https://colab.research.google.com/github/ckxmrls/kayedocs/blob/main/Assignment_6_MORALES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Linear Algebra for ECE

###Laboratory 6: Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

###Objectives
At the end of this activity you will be able to:

1.   Be familiar with the fundamental matrix operations.
2.   Apply the operations to solve intemediate equations.
3.   Apply algebra in engineering solutions.



### Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is doneby flipping the values of its elementsover its diagonals. 
$A^T$

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

This can now be achieved programmatically by using np.transpose() or using the T method.

In [ ]:
A = np.array([
              [1, 2, 5],
              [5, -1, 0],
              [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1],
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

### TRY

Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
M=np.array([
    [2,1,6],
    [1,3,4]        
])

In [ ]:
M.shape

(2, 3)

In [ ]:
np.transpose(M).shape

(3, 2)

In [ ]:
M.T.shape

(3, 2)

In [ ]:
MT= M.T
MT

array([[2, 1],
       [1, 3],
       [6, 4]])

##Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:



$$X = \begin{bmatrix}x_{(0,0)}&amp;x_{(0,1)}\\ x_{(1,0)}&amp;x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&amp;y_{(0,1)}\\ y_{(1,0)}&amp;y_{(1,1)}\end{bmatrix}$$
The dot product will then be computed as:$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} &amp; x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} &amp; x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:$$X = \begin{bmatrix}1&amp;2\\ 0&amp;1\end{bmatrix}, Y = \begin{bmatrix}-1&amp;0\\ 2&amp;2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 &amp; 1*0 + 2*2 \\  0*-1 + 1*2 &amp; 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 &amp; 4 \\2 &amp; 2 \end{bmatrix}$$
This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [ ]:
X = np.array([
              [1,2],
              [0,1],
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

##Rule 1: The inner dimensions of the two matrices in question must be the same.

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&amp;4\\5&amp;-2\\0&amp;1\end{bmatrix}, B = \begin{bmatrix}1&amp;1\\3&amp;3\\-1&amp;-2\end{bmatrix}, C = \begin{bmatrix}0&amp;1&amp;1\\1&amp;1&amp;2\end{bmatrix}$$
So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.

In [ ]:
C = np.array([
              [1,2,3],
              [0,1,2],
              [2,1,0]
])
K = np.array([
    [-1,0,1],
    [2,2,2],
    [1,2,3]
])

In [ ]:
np.dot(C,K)

array([[ 6, 10, 14],
       [ 4,  6,  8],
       [ 0,  2,  4]])

In [ ]:
C.dot(K)

array([[ 6, 10, 14],
       [ 4,  6,  8],
       [ 0,  2,  4]])

In [ ]:
C @ K

array([[ 6, 10, 14],
       [ 4,  6,  8],
       [ 0,  2,  4]])

In [ ]:
np.matmul(C,K)

array([[ 6, 10, 14],
       [ 4,  6,  8],
       [ 0,  2,  4]])

##Rule 2: Dot Product has special properties


Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:


1.   $A \cdot B \neq B \cdot A$
2.   $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
3. $A\cdot(B+C) = A\cdot B + A\cdot C$
4. $(B+C)\cdot A = B\cdot A + C\cdot A$
5. $A\cdot I = A$
6. $A\cdot \emptyset = \emptyset$

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
M = np.array([
              [1,2],
              [6, -2],
              [5,3]
])
E = np.array([
              [2,4],
              [8,7],
              [-4, -9]
])
B = np.array([
              [0,1,2],
              [9,1,1]
])
print(M.shape)
print(E.shape)
print(B.shape)

(3, 2)
(3, 2)
(2, 3)


In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
M.dot(np.eye(3))

array([[2., 1., 6.],
       [1., 3., 4.]])

In [ ]:
M @ B

array([[ 18,   3,   4],
       [-18,   4,  10],
       [ 27,   8,  13]])

In [ ]:
E @ B

array([[ 36,   6,   8],
       [ 63,  15,  23],
       [-81, -13, -17]])

In [ ]:
M @ E

ValueError: ignored

In [ ]:
X = np.array([
              [1,2,3,0]
])
Y = np.array([
             [1,0,4,-1] 
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [ ]:
Y.T@ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X @ Y.T

array([[13]])

In [ ]:
A = np.array([
              [4,2,1],
              [5,4,1],
              [2,1,3]
])
M= np.array([
             [3,5,7],
             [6,1,7],
             [3,1,8]
           

])
P= np.array([
             [1,1,8],
             [0,1,1],
             [1,9,1]
])
print(A.shape)
print(M.shape)
print(P.shape)



(3, 3)
(3, 3)
(3, 3)


In [ ]:
A1 = A @ M
A1

array([[27, 23, 50],
       [42, 30, 71],
       [21, 14, 45]])

In [ ]:
A2 = M @ A
A2

array([[51, 33, 29],
       [43, 23, 28],
       [33, 18, 28]])

In [ ]:
np.array_equiv(A1,A2)

False

##Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:$$A = \begin{bmatrix}a_{(0,0)}&amp;a_{(0,1)}\\a_{(1,0)}&amp;a_{(1,1)}\end{bmatrix}$$We can compute for the determinant as:$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$So if we have $A$ as:$$A = \begin{bmatrix}1&amp;4\\0&amp;3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using np.linalg.det().

In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
B = np.array([
              [1, 5, 2],
              [3, -1 ,-1],
              [0, -2, 1]
])
np.linalg.det(B)

-30.000000000000014

In [ ]:
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:$$M = \begin{bmatrix}1&amp;7\\-3&amp;5\end{bmatrix}$$First, we need to get the determinant of $M$.$$|M| = (1)(5)-(-3)(7) = 26$$Next, we need to reform the matrix into the inverse form:$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} &amp; -m_{(0,1)} \\ -m_{(1,0)} &amp; m_{(0,0)}\end{bmatrix}$$So that will be:$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 &amp; -7 \\ 3 &amp; 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} &amp; \frac{-7}{26} \\ \frac{3}{26} &amp; \frac{1}{26}\end{bmatrix}$$

For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use np.linalg.inv().

In [ ]:
M = np.array([
    [1,7],
    [-3, 5]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [6, 9, 0],
              [4, 2, -1],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [ ]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

In [ ]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])

# Activity

##Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [7]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
C = np.array([
              [9,2,1],
              [2,0,5],
              [0,3,2]
])
K = np.array([
              [1,4,7],
              [4,8,6],
              [6,3,1]
])
M = np.array([
              [3,5,4],
              [7,3,8],
              [9,5,1]
])

$A \cdot B \neq B \cdot A$

In [15]:
np.dot(C,K)

array([[23, 55, 76],
       [32, 23, 19],
       [24, 30, 20]])

In [16]:
np.dot(K,C)

array([[17, 23, 35],
       [52, 26, 56],
       [60, 15, 23]])

$A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [18]:
X = np.dot(K,M)
Y = np.dot(C,K)
Q = np.dot(C,X)
W = np.dot(Y,M)

In [19]:
print(Q)

[[1138  660  608]
 [ 428  324  331]
 [ 462  310  356]]


In [20]:
print(W)

[[1138  660  608]
 [ 428  324  331]
 [ 462  310  356]]


$A\cdot(B+C) = A\cdot B + A\cdot C$

In [21]:
D = K + M
print(D)

[[ 4  9 11]
 [11 11 14]
 [15  8  2]]


In [22]:
np.dot(C,D)

array([[ 73, 111, 129],
       [ 83,  58,  32],
       [ 63,  49,  46]])

In [23]:
E = np.dot(C,K)
print(E)

[[23 55 76]
 [32 23 19]
 [24 30 20]]


In [24]:
F = np.dot(C,K)
print(F)

[[23 55 76]
 [32 23 19]
 [24 30 20]]


In [25]:
E + F

array([[ 46, 110, 152],
       [ 64,  46,  38],
       [ 48,  60,  40]])

$(B+C)\cdot A = B\cdot A + C\cdot A$

In [26]:
np.dot((K+M),C)

array([[ 54,  41,  71],
       [121,  64,  94],
       [151,  36,  59]])

In [28]:
S = np.dot(K,C)
T = np.dot(M,C)

In [29]:
S + T

array([[ 54,  41,  71],
       [121,  64,  94],
       [151,  36,  59]])

$A\cdot I = A$

In [30]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
print(C)

[[9 2 1]
 [2 0 5]
 [0 3 2]]


In [33]:
np.dot(C,I)

array([[9., 2., 1.],
       [2., 0., 5.],
       [0., 3., 2.]])

$A\cdot \emptyset = \emptyset$ 

In [34]:
z_mat = np.zeros(C.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
a_dot_z = C.dot(np.zeros(C.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.array_equal(a_dot_z,z_mat)

True

In [38]:
null_mat = np.empty(C.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

##Conclusion

We came to the conclusion that at first we had a hard time knowing which codes needed to be used in for it to run so that some of the codes would execute correctly. I therefore conclude that this topic we will be able to develop a better intuition for machine learning and deep learning algorithms if you understand linear algebra we need to study linear algebra when most python can be accomplished with pre-existing modules and packages. As you will see, even the most fundamental tasks in data science and machine learning require some prior understanding of linear algebra.. This will allow you to select appropriate hyperparameters and build a better model.