<a href="https://colab.research.google.com/github/ckxmrls/kayedocs/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ECE
##Laboratory 4 :Matrices

## Objectives
At the end of this activity you will be able to:


1.   Be familiar with matrices and their relation to linear equation
2.   Perform basic matrx operations
3.   Program and translate matrixequations and operationsusing Python






##Discussion

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

## Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representation of complex equation or multiple inter - related equations from 2 dimentional equations to even hundreds and thousands of others

Let's say for example you have ***A*** and ***B*** as the system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that ***A*** is a system of 2 equations with 2 parameters, While ***B*** is a system of 3 equation with 3 parameters. We can represent
them as matrices:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

##Declaring Matrices
We must start the matrix, but we do not want to use a loop in a lengthier method. For that, we need an abstract. In dynamic programming, this sort of problem is extremely prevalent.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [11]:
## since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [18]:
## Declaring a 2 x 2 matrix
A = np.array([
             [1, 2],
             [3, 1]
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [19]:
G = np.array([
              [1, 1],
              [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [20]:
## Declaring a 3 x 2 matrix:
B = np.array([
              [8, 2],
              [5,4],
              [1, 1]       
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [22]:
H = np.array([1, 2, 3, 4, 5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



#Categorizing Matrices


There are several ways of classifying matrices. Once could be according to their **shape** and another is according to their **element values**. We'll try to go through them.

##According to Shape

###Raw and Column Matrices


Row and Column Matrices are common in vector and matrix computation. They can also represent row and column spaces of a bigger vector space. It is represented by a single column or a single row.

In [23]:
## Declaring a Row Matrix

row_mat_1D = np.array([
                       1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
                       [1, 2, 3]
]) ## this is a 2-D Matrix with a shape of (1, 3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [24]:
## Declaring a Column Matrix

col_mat = np.array([
                    [1],
                    [2],
                    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



##Square Matrices

Square Matrices are matrices that have the same row and column sizes. We could say a matrix is square if *i* - *j*. We can tweak our matrix descriptor function to determine square matrices.

In [26]:
def describe_mat(matrix):
  is_square = True if matrix.shape [0] -- matrix.shape[1] else False 
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [29]:
square_mat = np.array([
                             [1, 2, 5],
                             [3, 3, 0],
                             [6, 1, 2]
])

non_square_mat = np.array([
                           [1, 2, 5],
                           [3, 3, 0]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 0]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 0]]

Shape:	(2, 3)
Rank:	2
Is Square: True



##According to Element Values

##Null Matrix

A Null Matrix is a matrix that has element. It is always a subsplace of any vector or matrix. 